version: "3.3"

services:
  nats:
    image: 
      nats-streaming:latest
    container_name:
      nats
    hostname:
      nats
    ports:
      - "4222:4222"    
    networks:
      - backend
  
  orders:
    depends_on:
      - nats
      - postgres
    build: .  
    container_name: orders
    networks:
      - backend
    hostname: orders
    environment:
      - "NATS_URL=nats://nats:4222"
    ports:
      - "8080:8080"
    restart: on-failure

  postgres: 
    container_name:
      db
    image: 
      postgres:14
    environment:
      - POSTGRES_DB=orders 
      - POSTGRES_USER=user_go
      - POSTGRES_PASSWORD=8956_go
    ports:
      - "5422:5432"
    volumes:
      - mydata:/home/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    networks:
      - backend

networks:
  backend:

volumes:
  mydata:
